language: go

sudo: false

install:
  - go get -t -v ./...

script:
  - go build
  - ./mobi-promo-notify --mobi-provider mobifone --recipient-file ./recipients_mobifone.txt
  - ./mobi-promo-notify --mobi-provider viettel --recipient-file ./recipients_viettel.txt
  - ./mobi-promo-notify --mobi-provider vinaphone --recipient-file ./recipients_vinaphone.txt
